apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: artifactory-frontend-config
  namespace: jfrog-platform
spec:
  sslPolicy: "" # Optional: Reference a google_compute_ssl_policy if you have one
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT